# Builds the docs and deploys to GitHub pages

name: Deploy Docs to Github pages

permissions:
  contents: write

// TODO: Deploy on stable release instead
on:
  push:
    #tags:
    #  - v*
    branches:
      - master

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn docs

      - run: touch docs/.nojekyll
      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@releases/4.4.0
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
