name: Sync package.json with repository info
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2.3.4
      - name: Jaid/action-sync-node-meta
        uses: jaid/action-sync-node-meta@v2.0.0
        with:
          direction: overwrite-github
          githubToken: ${{ secrets.customGithubToken }}
