name: test
on:
  - workflow_call
jobs:
  run:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [14.x, 16.x, 18.x]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ./.github/actions/setup
        with:
          node-version: ${{matrix.node-version}}
      - run: yarn build
      - run: yarn test
